--------------------------------------------------------
--  Constraints for Table ORDER_ITEM
--------------------------------------------------------

  ALTER TABLE "C##IRTIZA"."ORDER_ITEM" MODIFY ("ORDER_ITEM_ID" NOT NULL ENABLE);
  ALTER TABLE "C##IRTIZA"."ORDER_ITEM" MODIFY ("QUANTITY" NOT NULL ENABLE);
  ALTER TABLE "C##IRTIZA"."ORDER_ITEM" MODIFY ("UNIT_PRICE" NOT NULL ENABLE);
  ALTER TABLE "C##IRTIZA"."ORDER_ITEM" MODIFY ("TOTAL_PRICE" NOT NULL ENABLE);
  ALTER TABLE "C##IRTIZA"."ORDER_ITEM" ADD PRIMARY KEY ("ORDER_ITEM_ID")
  USING INDEX  ENABLE;
