--------------------------------------------------------
--  Constraints for Table ORDERS
--------------------------------------------------------

  ALTER TABLE "C##IRTIZA"."ORDERS" MODIFY ("ORDER_ID" NOT NULL ENABLE);
  ALTER TABLE "C##IRTIZA"."ORDERS" MODIFY ("ORDER_DATE" NOT NULL ENABLE);
  ALTER TABLE "C##IRTIZA"."ORDERS" MODIFY ("SHIPPING_ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "C##IRTIZA"."ORDERS" MODIFY ("TOTAL_COST" NOT NULL ENABLE);
  ALTER TABLE "C##IRTIZA"."ORDERS" MODIFY ("SUBTOTAL" NOT NULL ENABLE);
  ALTER TABLE "C##IRTIZA"."ORDERS" MODIFY ("SHIPPING_COST" NOT NULL ENABLE);
  ALTER TABLE "C##IRTIZA"."ORDERS" MODIFY ("TAX" NOT NULL ENABLE);
  ALTER TABLE "C##IRTIZA"."ORDERS" ADD PRIMARY KEY ("ORDER_ID")
  USING INDEX  ENABLE;
