--------------------------------------------------------
--  Constraints for Table PRODUCT_CATEGORY
--------------------------------------------------------

  ALTER TABLE "C##IRTIZA"."PRODUCT_CATEGORY" MODIFY ("PRODUCT_ID" NOT NULL ENABLE);
  ALTER TABLE "C##IRTIZA"."PRODUCT_CATEGORY" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "C##IRTIZA"."PRODUCT_CATEGORY" MODIFY ("PRICE" NOT NULL ENABLE);
  ALTER TABLE "C##IRTIZA"."PRODUCT_CATEGORY" MODIFY ("STOCK" NOT NULL ENABLE);
  ALTER TABLE "C##IRTIZA"."PRODUCT_CATEGORY" ADD PRIMARY KEY ("PRODUCT_ID")
  USING INDEX  ENABLE;
