--------------------------------------------------------
--  Constraints for Table SELLER
--------------------------------------------------------

  ALTER TABLE "C##IRTIZA"."SELLER" MODIFY ("SELLER_ID" NOT NULL ENABLE);
  ALTER TABLE "C##IRTIZA"."SELLER" MODIFY ("FIRST_NAME" NOT NULL ENABLE);
  ALTER TABLE "C##IRTIZA"."SELLER" MODIFY ("LAST_NAME" NOT NULL ENABLE);
  ALTER TABLE "C##IRTIZA"."SELLER" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "C##IRTIZA"."SELLER" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "C##IRTIZA"."SELLER" MODIFY ("PHONE" NOT NULL ENABLE);
  ALTER TABLE "C##IRTIZA"."SELLER" MODIFY ("ADDRESS" NOT NULL ENABLE);
  ALTER TABLE "C##IRTIZA"."SELLER" ADD PRIMARY KEY ("SELLER_ID")
  USING INDEX  ENABLE;
  ALTER TABLE "C##IRTIZA"."SELLER" ADD UNIQUE ("EMAIL")
  USING INDEX  ENABLE;
