--------------------------------------------------------
--  DDL for Table PRODUCT_STORE
--------------------------------------------------------

  CREATE TABLE "C##IRTIZA"."PRODUCT_STORE" 
   (	"PRODUCT_STORE_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"PRODUCT_ID" NUMBER, 
	"STORE_ID" NUMBER, 
	"STOCK_QUANTITY" NUMBER, 
	"DISCOUNT" NUMBER
   ) ;
