--------------------------------------------------------
--  DDL for Table PRODUCT_CATEGORY
--------------------------------------------------------

  CREATE TABLE "C##IRTIZA"."PRODUCT_CATEGORY" 
   (	"PRODUCT_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NAME" VARCHAR2(255 BYTE), 
	"PRICE" NUMBER, 
	"STOCK" NUMBER, 
	"SOLD" NUMBER DEFAULT 0, 
	"RATING" NUMBER DEFAULT 0, 
	"DESCRIPTION" VARCHAR2(1000 BYTE), 
	"IMAGES" VARCHAR2(1000 BYTE), 
	"DEAL_NEWPRICE" NUMBER, 
	"OWNER" NUMBER, 
	"CATEGORY" VARCHAR2(255 BYTE)
   ) ;
