--------------------------------------------------------
--  DDL for Table STORE
--------------------------------------------------------

  CREATE TABLE "C##IRTIZA"."STORE" 
   (	"STORE_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"STORE_NAME" VARCHAR2(255 BYTE), 
	"STORE_OWNER" NUMBER, 
	"CONTACT_INFO" VARCHAR2(50 BYTE), 
	"DESCRIPTION" VARCHAR2(1000 BYTE), 
	"CREATION_DATE" DATE
   ) ;
