--------------------------------------------------------
--  File created - Monday-December-04-2023   
--------------------------------------------------------
@D:\New Folder (2)\TABLES\BUYER.sql
@D:\New Folder (2)\TABLES\CART.sql
@D:\New Folder (2)\TABLES\CATEGORY.sql
@D:\New Folder (2)\TABLES\ORDERS.sql
@D:\New Folder (2)\TABLES\ORDER_ITEM.sql
@D:\New Folder (2)\TABLES\PRODUCT_CATEGORY.sql
@D:\New Folder (2)\TABLES\PRODUCT_STORE.sql
@D:\New Folder (2)\TABLES\SELLER.sql
@D:\New Folder (2)\TABLES\STORE.sql
@D:\New Folder (2)\TABLES\WISHLIST.sql
@D:\New Folder (2)\INDEXES\SYS_C007471.sql
@D:\New Folder (2)\INDEXES\SYS_C007520.sql
@D:\New Folder (2)\INDEXES\SYS_C007521.sql
@D:\New Folder (2)\INDEXES\SYS_C007529.sql
@D:\New Folder (2)\INDEXES\SYS_C007530.sql
@D:\New Folder (2)\INDEXES\SYS_C007553.sql
@D:\New Folder (2)\INDEXES\SYS_C007560.sql
@D:\New Folder (2)\INDEXES\SYS_C007606.sql
@D:\New Folder (2)\INDEXES\SYS_C007611.sql
@D:\New Folder (2)\INDEXES\SYS_C007615.sql
@D:\New Folder (2)\INDEXES\SYS_C007622.sql
@D:\New Folder (2)\INDEXES\SYS_C007630.sql
@D:\New Folder (2)\INDEXES\SYS_C007520_1.sql
@D:\New Folder (2)\INDEXES\SYS_C007521_1.sql
@D:\New Folder (2)\INDEXES\SYS_C007611_1.sql
@D:\New Folder (2)\INDEXES\SYS_C007630_1.sql
@D:\New Folder (2)\INDEXES\SYS_C007553_1.sql
@D:\New Folder (2)\INDEXES\SYS_C007560_1.sql
@D:\New Folder (2)\INDEXES\SYS_C007471_1.sql
@D:\New Folder (2)\INDEXES\SYS_C007622_1.sql
@D:\New Folder (2)\INDEXES\SYS_C007529_1.sql
@D:\New Folder (2)\INDEXES\SYS_C007530_1.sql
@D:\New Folder (2)\INDEXES\SYS_C007615_1.sql
@D:\New Folder (2)\INDEXES\SYS_C007606_1.sql
@D:\New Folder (2)\TRIGGERS\TRG_BEFORE_STOCK_UPDATE.sql
@D:\New Folder (2)\TRIGGERS\TRG_CALCULATE_TOTAL_PRICE.sql
@D:\New Folder (2)\TRIGGERS\TRG_INSERT_PRODUCT_STORE.sql
@D:\New Folder (2)\TRIGGERS\TRG_VALIDATE_UNIT_PRICE.sql
@D:\New Folder (2)\TRIGGERS\TRG_VALIDATE_UNIT_PRICE_1.sql
@D:\New Folder (2)\TRIGGERS\TRG_CALCULATE_TOTAL_PRICE_1.sql
@D:\New Folder (2)\TRIGGERS\TRG_BEFORE_STOCK_UPDATE_1.sql
@D:\New Folder (2)\TRIGGERS\TRG_INSERT_PRODUCT_STORE_1.sql
@D:\New Folder (2)\PROCEDURES\CREATESELLERANDSTORE.sql
@D:\New Folder (2)\CONSTRAINTS\BUYER.sql
@D:\New Folder (2)\CONSTRAINTS\CART.sql
@D:\New Folder (2)\CONSTRAINTS\CATEGORY.sql
@D:\New Folder (2)\CONSTRAINTS\ORDERS.sql
@D:\New Folder (2)\CONSTRAINTS\ORDER_ITEM.sql
@D:\New Folder (2)\CONSTRAINTS\PRODUCT_CATEGORY.sql
@D:\New Folder (2)\CONSTRAINTS\PRODUCT_STORE.sql
@D:\New Folder (2)\CONSTRAINTS\SELLER.sql
@D:\New Folder (2)\CONSTRAINTS\STORE.sql
@D:\New Folder (2)\CONSTRAINTS\WISHLIST.sql
@D:\New Folder (2)\REF_CONSTRAINTS\CART.sql
@D:\New Folder (2)\REF_CONSTRAINTS\ORDERS.sql
@D:\New Folder (2)\REF_CONSTRAINTS\ORDER_ITEM.sql
@D:\New Folder (2)\REF_CONSTRAINTS\PRODUCT_CATEGORY.sql
@D:\New Folder (2)\REF_CONSTRAINTS\PRODUCT_STORE.sql
@D:\New Folder (2)\REF_CONSTRAINTS\STORE.sql
@D:\New Folder (2)\REF_CONSTRAINTS\WISHLIST.sql
